import  requests
from  bs4 import  BeautifulSoup
import xlwt
from xlrd import open_workbook
from xlutils.copy import copy





# 设置Excel样式
def set_style(name, height, bold=False):
    style = xlwt.XFStyle()  # 初始化样式
    font = xlwt.Font()  # 为样式创建字体
    font.name = name  # 'Times New Roman'
    font.bold = bold
    font.color_index = 4
    font.height = height
    style.font = font
    return style

def getTableByPage(curPage,nextPage):
    url = "http://www.szsti.gov.cn/services/hightech/default.aspx"
    from_data = {
        "PagerControl_input": str(curPage),
        "__EVENTARGUMENT": str(nextPage),
        "__EVENTTARGET": "PagerControl",
        "__EVENTVALIDATION": "/wEdAAEAAAD/////AQAAAAAAAAAPAQAAAAYAAAAIR6EBhXahAYV1oQGFdKEBhRwU3f3MQ+d8CwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJk3QAUPJr17ntVowFFRVa3ASeR3R0u0HpmlE0yngEF",
        "__VIEWSTATE": "/wEMDAwQAgAADgEMBQAMEAIAAA4DDAUBDBACDAAMCBAEEAUAAQblhajpg6gBAAgIEAUAAQzlm73lrrbpq5jkvIEBATEJCBAFAAEP5rex5Zyz5biC6auY5LyBAQEyCQgQBQABDOmrmOmhueiupOWumgEBMwkIAAAMBQcMEAIPAQEFSXRlbXMFFAAOFAwFAQwQAgAADgYMBQEMEAIcGg1TeXN0ZW0uU3RyaW5nS21zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OQEBBTEzMDc0AAAMBQMMEAIcGwkAAQEKU1oyMDE2MTA2NgAADAUFDBACHBsJAAEBJOmRq+WFg+enkeaKgO+8iOa3seWcs++8ieaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBLea3seWcs+W4guWNl+WxseWMuuenkeaKgOW3peS4muWbree7tOeUqOWkp+WOpgAADAUJDBACHBsJAAEBBui9r+S7tgAADAULDBACHBsJAAECBAAAAAwFAgwQAgAADgYMBQEMEAIcGwkAAQEFMTMwNzMAAAwFAwwQAhwbCQABAQlTWjIwMTYyMDUAAAwFBQwQAhwbCQABASrljY/lkoznjq/kv53np5HmioDvvIjmt7HlnLPvvInmnInpmZDlhazlj7gAAAwFBwwQAhwbCQABAVzmt7HlnLPluILpvpnljY7mlrDljLrlpKfmtarlip7kuovlpITlpKfmtarnpL7ljLrljY7lroHot6/ljY7ogZTlt6XkuJrlm60xMOWPt+WOguaIv+esrOS4gOWxggAADAUJDBACHBsJAAEBFeawtOaxoeafk+aOp+WItuaKgOacrwAADAULDBACHBsJAAECBAAAAAwFAwwQAgAADgYMBQEMEAIcGwkAAQEFMTMwNzIAAAwFAwwQAhwbCQABAQpTWjIwMTYxMTcxAAAMBQUMEAIcGwkAAQEq5pmT6IO95LqS6IGU56eR5oqA77yI5rex5Zyz77yJ5pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQFF5rex5Zyz5biC5a6d5a6J5Yy65paw5a6J6KGX6YGTNTDljLrljY7mtbfllYbliqHlpKfljqZC5qCL5Zub5qW8NDA25Y+3AAAMBQkMEAIcGwkAAQEb6K6h566X5py65Y+K5YW257uI56uv5oqA5pyvAAAMBQsMEAIcGwkAAQIEAAAADAUEDBACAAAOBgwFAQwQAhwbCQABAQUxMzA3MQAADAUDDBACHBsJAAEBCVNaMjAxNjY0MQAADAUFDBACHBsJAAEBKuS8n+iDveacuueUteiuvuWkh++8iOa3seWcs++8ieaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBQOa3seWcs+W4guWuneWuieWMuuadvuWyl+ihl+mBk+eHleW3neWMl+mDqOW3peS4muWbrUI35qCL44CBQzbmoIsAAAwFCQwQAhwbCQABASfnlLXlipvns7vnu5/kv6Hmga/ljJbkuI7oh6rliqjljJbmioDmnK8AAAwFCwwQAhwbCQABAgQAAAAMBQUMEAIAAA4GDAUBDBACHBsJAAEBBTEzMDcwAAAMBQMMEAIcGwkAAQEJU1oyMDE2ODgxAAAMBQUMEAIcGwkAAQEt5Lyf5Yib6L6+55S15a2Q56eR5oqA77yI5rex5Zyz77yJ5pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQFF5rex5Zyz5biC5Y2X5bGx5Yy66auY5paw5Lit5Zub6YGTMzDlj7fpvpnms7DliKnlpKfljqblha3mpbw2MzAtNjMz5a6kAAAMBQkMEAIcGwkAAQEV572R57uc5Y+K6YCa5L+h5oqA5pyvAAAMBQsMEAIcGwkAAQIEAAAADAUGDBACAAAOBgwFAQwQAhwbCQABAQUxMzA2OQAADAUDDBACHBsJAAEBCVNaMjAxNjc0MwAADAUFDBACHBsJAAEBKue7tOWHhueUteWtkOenkeaKgO+8iOa3seWcs++8ieaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBT+a3seWcs+W4guWNl+WxseWMuuahg+a6kOihl+mBk+eVmeS7meWkp+mBkzEyMTPlj7fkvJflhqDnuqLoirHlsq3ljZc15Yy6M+agizLmpbwAAAwFCQwQAhwbCQABAhgAAAAMBQsMEAIcGwkAAQIEAAAADAUHDBACAAAOBgwFAQwQAhwbCQABAQUxMzA2OAAADAUDDBACHBsJAAEBCVNaMjAxNjQyMQAADAUFDBACHBsJAAEBEuW+ruaXheaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBROa3seWcs+W4guemj+eUsOWMuuemj+WNjuS4gOi3r+WFreWPt+WFjeeojuWVhuWKoeWkp+WOpuijmealvOilvzAz5bGCAAAMBQkMEAIcGwkAAQIOAAAADAULDBACHBsJAAECBAAAAAwFCAwQAgAADgYMBQEMEAIcGwkAAQEFMTMwNjcAAAwFAwwQAhwbCQABAQlTWjIwMTYyODYAAAwFBQwQAhwbCQABASrkuIfnu7Tnjq/nkIPnp5HmioDvvIjmt7HlnLPvvInmnInpmZDlhazlj7gAAAwFBwwQAhwbCQABAUPmt7HlnLPluILljZflsbHljLrljJfnjq/ot6/nrKzkupTlt6XkuJrljLrpo47kupHnp5HmioDlpKfljqYxMDHkuYsyAAAMBQkMEAIcGwkAAQIYAAAADAULDBACHBsJAAECBAAAAAwFCQwQAgAADgYMBQEMEAIcGwkAAQEFMTMwNjYAAAwFAwwQAhwbCQABAQlTWjIwMTYxMTIAAAwFBQwQAhwbCQABARjlpKnoiKrnp5HmioDmnInpmZDlhazlj7gAAAwFBwwQAhwbCQABAUHlub/kuJznnIHmt7HlnLPluILljZflsbHljLrnp5HmioDljZfljYHkuozot6/mlrnlpKflpKfljqYyMDUtLTIwNwAADAUJDBACHBsJAAECDgAAAAwFCwwQAhwbCQABAgQAAAAMBQoMEAIAAA4GDAUBDBACHBsJAAEBBTEzMDY1AAAMBQMMEAIcGwkAAQEJU1oyMDE2NzA3AAAMBQUMEAIcGwkAAQEt6aG65pmv5Zut57K+5a+G6ZO46YCg77yI5rex5Zyz77yJ5pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQFK5rex5Zyz5biC6b6Z5Y2O5paw5Yy66KeC5r6c6KGX6YGT5Li55rmW56S+5Yy65rOX6buO6Lev5r6c5aGY5bel5Lia5Yy6MTbmoIsAAAwFCQwQAhwbCQABAQzph5HlsZ7mnZDmlpkAAAwFCwwQAhwbCQABAgQAAAAMBQsMEAIAAA4GDAUBDBACHBsJAAEBBTEzMDY0AAAMBQMMEAIcGwkAAQEJU1oyMDE2NzM3AAAMBQUMEAIcGwkAAQEz55Sf54mp5rqQ55Sf54mp5oqA5pyv77yI5rex5Zyz77yJ6IKh5Lu95pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQEw5rex5Zyz5biC5Z2q5bGx5paw5Yy65Z2q5bGx6KGX6YGT5Z2q6JG16LevMjAw5Y+3AAAMBQkMEAIcGwkAAQES5Yac5Lia55Sf54mp5oqA5pyvAAAMBQsMEAIcGwkAAQIEAAAADAUMDBACAAAOBgwFAQwQAhwbCQABAQUxMzA2MwAADAUDDBACHBsJAAEBCVNaMjAxNjkyOQAADAUFDBACHBsJAAEBHua3seWcs+e6teaoqui9r+S7tuaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBPOa3seWcs+W4guemj+eUsOWMuue6ouWyreWMl+i3r+WFiOenkeacuueUteWkp+WOpjEzMTEtMTMxM+WupAAADAUJDBACHBsJAAECDgAAAAwFCwwQAhwbCQABAgQAAAAMBQ0MEAIAAA4GDAUBDBACHBsJAAEBBTEzMDYyAAAMBQMMEAIcGwkAAQEJU1oyMDE2NDg3AAAMBQUMEAIcGwkAAQEk5rex5Zyz5Li75Z+O572R57uc56eR5oqA5pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQFH5rex5Zyz5biC5Y2X5bGx5Yy65oub5ZWG6KGX6YGT5Y2X5rW35aSn6YGT6Iqx5qC35bm0576O5bm05bm/5Zy6MeagizTmpbwAAAwFCQwQAhwbCQABAg4AAAAMBQsMEAIcGwkAAQIEAAAADAUODBACAAAOBgwFAQwQAhwbCQABAQUxMzA2MQAADAUDDBACHBsJAAEBCVNaMjAxNjQyOAAADAUFDBACHBsJAAEBKua3seWcs+a0sumZhemAmuiIquaKlei1hOaOp+iCoeaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBa+a3seWcs+W4guWJjea1t+a3sea4r+WQiOS9nOWMuuWJjea5vuS4gOi3rzHlj7dB5qCLMjAx5a6k77yI5YWl6am75rex5Zyz5biC5YmN5rW35ZWG5Yqh56eY5Lmm5pyJ6ZmQ5YWs5Y+477yJAAAMBQkMEAIcGwkAAQEM6Iiq5aSp5oqA5pyvAAAMBQsMEAIcGwkAAQIEAAAADAUPDBACAAAOBgwFAQwQAhwbCQABAQUxMzA2MAAADAUDDBACHBsJAAEBCVNaMjAxNjY1OQAADAUFDBACHBsJAAEBKua3seWcs+S4reaZuue7j+a1juaKgOacr+WQiOS9nOaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBPea3seWcs+W4guemj+eUsOWMuua3seWNl+S4rei3rzEwMDLlj7fmlrDpl7vlpKfljqYx5Y+35qW8MzHlsYIAAAwFCQwQAhwbCQABAR7kv6Hmga/mioDmnK/kuJrliqHmtYHnqIvlpJbljIUAAAwFCwwQAhwbCQABAgQAAAAMBRAMEAIAAA4GDAUBDBACHBsJAAEBBTEzMDU5AAAMBQMMEAIcGwkAAQEJU1oyMDE2ODUyAAAMBQUMEAIcGwkAAQEk5rex5Zyz5Lit55uI5Yib5bGV56eR5oqA5pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQFE5rex5Zyz5biC5Y2X5bGx5Yy65qGD5rqQ6KGX6YGT57qi6Iqx5bKt5bel5Lia5Zut56ysNeWMukIx5qCLOOalvDHlj7cAAAwFCQwQAhwbCQABARLmmbrog73kuqTpgJrmioDmnK8AAAwFCwwQAhwbCQABAgQAAAAMBREMEAIAAA4GDAUBDBACHBsJAAEBBTEzMDU4AAAMBQMMEAIcGwkAAQEJU1oyMDE2MTYzAAAMBQUMEAIcGwkAAQEq5rex5Zyz5Lit6K6k6YCa5rWL5qOA6aqM5oqA5pyv5pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQFM5rex5Zyz5biC6b6Z5Y2O5paw5Yy66KeC5r6c6KGX6YGT6auY5paw5oqA5pyv5Lqn5Lia5Zut5ZiJ5rOJ5aSn5Y6mMuagizEtMuWxggAADAUJDBACHBsJAAEBDOWFseaAp+aKgOacrwAADAULDBACHBsJAAECBAAAAAwFEgwQAgAADgYMBQEMEAIcGwkAAQEFMTMwNTcAAAwFAwwQAhwbCQABAQpTWjIwMTYxMDEzAAAMBQUMEAIcGwkAAQEn5rex5Zyz5Lit56eR5pm65pif6YCa56eR5oqA5pyJ6ZmQ5YWs5Y+4AAAMBQcMEAIcGwkAAQFb5rex5Zyz5biC5a6d5a6J5Yy65paw5a6J6KGX6YGT5Yib5Lia5LqM6LevMjjljLrlrp3lronpm4blm6LnrKzkuIDlt6XkuJrln4445qCLMjA2LTIxMOWOguaIvwAADAUJDBACHBsJAAECIgAAAAwFCwwQAhwbCQABAgQAAAAMBRMMEAIAAA4GDAUBDBACHBsJAAEBBTEzMDU2AAAMBQMMEAIcGwkAAQEKU1oyMDE2MTEwNgAADAUFDBACHBsJAAEBJOa3seWcs+S4reenkemjnua1i+enkeaKgOaciemZkOWFrOWPuAAADAUHDBACHBsJAAEBa+a3seWcs+W4guWFieaYjuaWsOWMuuWFieaYjuihl+mBk+mrmOaWsOWMuumrmOaWsOi3rzEx5Y+356CU56Wl56eR5oqA5bel5Lia5Zut5py65qKw5Y6C5oi/5LqM5qW86KW/5L6n5Y2V5YWDAAAMBQkMEAIcGwkAAQEP5b6u55S15a2Q5oqA5pyvAAAMBQsMEAIcGwkAAQIEAAAADAUUDBACAAAOBgwFAQwQAhwbCQABAQUxMzA1NQAADAUDDBACHBsJAAEBCVNaMjAxNjA0MAAADAUFDBACHBsJAAEBJOa3seWcs+S4reaBkuajgOa1i+aKgOacr+aciemZkOWFrOWPuAAADAUHDBACHBsJAAEBYea3seWcs+W4guWuneWuieWMuuadvuWyl+ihl+mBk+WhmOS4i+a2jOekvuWMuuS6jOadkeiHtOWSjOi3r+W5v+ebm+Wkp+WOpuS6jOalvDIwMSjlip7lhazlnLrmiYDvvIkAAAwFCQwQAhwbCQABAlgAAAAMBQsMEAIcGwkAAQIEAAAADAUJDBACDA8CAQtSZWNvcmRjb3VudAQmMwAAARBDdXJyZW50UGFnZUluZGV4BQIPAQEMU2hvd0lucHV0Qm94AQZBbHdheXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSNyrC6ulzXwPOghxQO8EwzDUu8Qkh5aHGXqtfWwzzhQ==",
        "ddlEnterpriseType": "",
        "txtEnterpriseName": ""
    }

    response = requests.post(url, data=from_data)
    print(response.status_code)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        target = soup.find(id="data_list_container").findAll("tr")
        rexcel = open_workbook("TokyoHot.xls")
        row = rexcel.sheets()[0].nrows
        excel = copy(rexcel)
        table = excel.get_sheet(0)
        for tr in target[1:]:  # ignore th
            tds = tr.findAll("td")  # 获取所有的 td
            td = [x for x in tds]
            index = td[0].text.strip()
            serialNo = td[1].text.strip()
            companyName = td[2].text.strip()
            location = td[3].text.strip()
            domain = td[4].text.strip()
            category = td[5].text.strip()
            table.write(row, 0, index, set_style('Arial', 220))
            table.write(row,  1, serialNo, set_style('Arial', 220))
            table.write(row, 2, companyName, set_style('Arial', 220))
            table.write(row,  3, location, set_style('Arial', 220))
            table.write(row, 4, domain, set_style('Arial', 220))
            table.write(row,  5, category, set_style('Arial', 220))
            row = row + 1
        excel.save('TokyoHot.xls')
    else:
        print("500 Error")
        getTableByPage(curPage=curPage,nextPage=nextPage)


def getFirstPage():
    response = requests.get("http://www.szsti.gov.cn/services/hightech/default.aspx")
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        target = soup.find(id="data_list_container").findAll("tr")
        rexcel = open_workbook("TokyoHot.xls")
        row = rexcel.sheets()[0].nrows
        excel = copy(rexcel)
        table = excel.get_sheet(0)
        for tr in target[1:]:  # ignore th
            tds = tr.findAll("td")  # 获取所有的 td
            td = [x for x in tds]
            index = td[0].text.strip()
            serialNo = td[1].text.strip()
            companyName = td[2].text.strip()
            location = td[3].text.strip()
            domain = td[4].text.strip()
            category = td[5].text.strip()
            table.write(row, 0, index, set_style('Arial', 220))
            table.write(row, 1, serialNo, set_style('Arial', 220))
            table.write(row, 2, companyName, set_style('Arial', 220))
            table.write(row, 3, location, set_style('Arial', 220))
            table.write(row, 4, domain, set_style('Arial', 220))
            table.write(row, 5, category, set_style('Arial', 220))
            row = row + 1
        excel.save('TokyoHot.xls')
    else:
        print("firstPage 500 Error")
        getFirstPage()

def pa(curPage=None,nextPage=None):
    while curPage != 1:
        getTableByPage(curPage=curPage, nextPage=nextPage)
        curPage -= 1
        nextPage -= 1
    getFirstPage()

pa(654,655)